---
- name: Windows worker node join cluster
  hosts: workers_win
  vars_files:
    - variables.yml


  tasks:  
    - name: Test Connection
      win_ping:
    
    - name: Copy K8s join command from Ansible controller to windows host
      win_copy:
        src: "/home/{{ user }}/join-command-windows.ps1"
        dest: "{{ k8s_install_dir_windows }}\\join-command-windows.ps1"
        remote_src: no
        force: yes
    
    - name: Run K8s join command
      win_shell: "{{ k8s_install_dir_windows }}\\join-command-windows.ps1"
      register: k8s_join_output

    - name: Print K8s join output
      debug:
        msg: "{{ k8s_join_output.stdout_lines }}"